modLoader="javafml" #mandatory
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/benjilebon/SaphyreMod/issues"
[[mods]] #mandatory
modId="saphyre"
version="${file.jarVersion}"
displayName="Saphyre"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
credits="Aze (benjilebon), Winigan & Elodias" #optional
authors="Aze (benjilebon), Winigan"
description='The Saphyre'
[[dependencies.saphyre]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.saphyre]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.saphyre]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.36,)"
    ordering="NONE"
    side="BOTH"
